name: Deploy Static Website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        # Use secrets or IAM role configuration here

      - name: Upload to S3 bucket
        run: aws s3 cp Index.html s3://popstots/  # Replace with your file and bucket name
